import type { CompiledRuleSet } from "../schematron";
import en16931Cii from "./en16931-cii.json";
import en16931Ubl from "./en16931-ubl.json";
import info from "./info.json";
import xrechnungCii from "./xrechnung-cii.json";
import xrechnungUbl from "./xrechnung-ubl.json";

export type RuleSetId = "en16931-ubl" | "en16931-cii" | "xrechnung-ubl" | "xrechnung-cii";

export interface RuleSetInfo {
  id: RuleSetId;
  name: string;
  /** Version of the vendored rule set, e.g. "1.3.16". */
  version: string;
  /** Release of the upstream project the files were taken from, as named upstream. */
  release: string;
  /** Who publishes the rule set. */
  publisher: string;
  /** Where it is published (repository URL). */
  source: string;
  /** SPDX identifier of the licence of the rule set. */
  license: string;
  /** Number of rules (Schematron assertions) in the compiled rule set. */
  rules: number;
}

/** The bundled official rule sets and their versions (generated by `pnpm rules`). */
export const RULE_SETS = info as unknown as Record<RuleSetId, RuleSetInfo>;

/** Information about the bundled rule sets, or about one of them when given its id. */
export function ruleSetInfo(): RuleSetInfo[];
export function ruleSetInfo(id: RuleSetId): RuleSetInfo;
export function ruleSetInfo(id?: RuleSetId): RuleSetInfo | RuleSetInfo[] {
  return id ? RULE_SETS[id] : Object.values(RULE_SETS);
}

const compiled: Record<RuleSetId, CompiledRuleSet> = {
  "en16931-ubl": en16931Ubl as unknown as CompiledRuleSet,
  "en16931-cii": en16931Cii as unknown as CompiledRuleSet,
  "xrechnung-ubl": xrechnungUbl as unknown as CompiledRuleSet,
  "xrechnung-cii": xrechnungCii as unknown as CompiledRuleSet,
};

export function ruleSet(id: RuleSetId): CompiledRuleSet {
  return compiled[id];
}
